### ISSUE TITLE
No Implicit coversion of Time into String

### ISSUE THREAD

**Issue by bwlang** [QueueClassic/queue_classic#314]
I see this error in my logs:

```
  TypeError: no implicit conversion of Time into String
 .5.0/bundler/gems/queue_classic-4cdc9b8e804b/lib/queue_classic/queue.rb:81:in `block (2 levels) in lock'
.5.0/bundler/gems/queue_classic-4cdc9b8e804b/lib/queue_classic/queue.rb:75:in `tap'
.5.0/bundler/gems/queue_classic-4cdc9b8e804b/lib/queue_classic/queue.rb:75:in `block in lock'
.5.0/bundler/gems/queue_classic-4cdc9b8e804b/lib/queue_classic.rb:70:in `log_yield'
.5.0/bundler/gems/queue_classic-4cdc9b8e804b/lib/queue_classic/queue.rb:72:in `lock'
.5.0/bundler/gems/queue_classic-4cdc9b8e804b/lib/queue_classic/worker.rb:92:in `block in lock_job'
.5.0/bundler/gems/queue_classic-4cdc9b8e804b/lib/queue_classic/worker.rb:91:in `each'
.5.0/bundler/gems/queue_classic-4cdc9b8e804b/lib/queue_classic/worker.rb:91:in `lock_job'
.5.0/bundler/gems/queue_classic-4cdc9b8e804b/lib/queue_classic/worker.rb:72:in `work'
.5.0/bundler/gems/queue_classic-4cdc9b8e804b/lib/queue_classic/worker.rb:46:in `start'
.5.0/bundler/gems/queue_classic-4cdc9b8e804b/lib/queue_classic/tasks.rb:27:in `block (2 levels) in <main>'
```
I think that line 81 is already a Time object when it comes back from the db... the quick fix of adding .to_s seems to be fine for my situation - but I'll propose a better option in a sec.

**Comment by ukd1** [comment]
Fixed by #325
